/*
 * All words shown in the app, in each language.
 * To add a language, copy the "en" block, give it a new code (for example "gu"),
 * translate the right-hand side, and add the code to LANGS below.
 */
const LANGS = [
  { code: 'hi', name: 'हिंदी' },
  { code: 'en', name: 'English' }
];

const STRINGS = {
  hi: {
    appName: 'जिनवाणी',
    greeting: 'जय जिनेन्द्र',
    chooseLang: 'भाषा चुनें',
    changeLater: 'बाद में सेटिंग में बदल सकते हैं',
    continueReading: 'पढ़ना जारी रखें',
    startReading: 'यहाँ से शुरू करें',
    books: 'ग्रंथ',
    search: 'खोजें',
    saved: 'सहेजे गए',
    settings: 'सेटिंग',
    home: 'मुख्य',
    back: 'वापस',
    contents: 'सूची',
    prev: 'पीछे',
    next: 'आगे',
    finish: 'समाप्त',
    listen: 'सुनें',
    stop: 'रोकें',
    save: 'सहेजें',
    savedDone: 'सहेजा गया',
    removed: 'हटा दिया',
    remove: 'हटाएँ',
    todaysSutra: 'आज का सूत्र',
    readFromStart: 'शुरू से पढ़ें',
    resumeAt: 'जहाँ छोड़ा था',
    goToNumber: 'नंबर पर जाएँ',
    go: 'जाएँ',
    numberHint: '1 से {n} तक',
    badNumber: '1 से {n} के बीच नंबर लिखें',
    meaning: 'अर्थ',
    firstVerseNote: 'यह पहला है',
    bookDone: 'ग्रंथ पूर्ण हुआ',
    reportMistake: 'पाठ में गलती? बताएँ',
    searchPlaceholder: 'जैसे: भक्तामर, सम्यग्दर्शन',
    speak: 'बोलकर खोजें',
    listening: 'सुन रहे हैं… बोलिए',
    noResults: 'कुछ नहीं मिला। दूसरा शब्द लिखकर देखें।',
    resultsBooks: 'ग्रंथ',
    resultsText: 'पाठ में',
    typeToSearch: 'ग्रंथ का नाम या कोई शब्द लिखें, या माइक दबाकर बोलें।',
    noBookmarks: 'अभी कुछ सहेजा नहीं गया। पढ़ते समय "सहेजें" दबाएँ।',
    noVoice: 'इस फ़ोन में हिंदी आवाज़ नहीं मिली। फ़ोन की सेटिंग में "Text-to-speech" में हिंदी जोड़ें।',
    noSpeech: 'इस ब्राउज़र में सुनने की सुविधा नहीं है।',
    noMic: 'इस ब्राउज़र में बोलकर खोजना उपलब्ध नहीं है। लिखकर खोजें।',
    micDenied: 'माइक की अनुमति नहीं मिली।',
    loading: 'खुल रहा है…',
    loadError: 'खुल नहीं पाया। इंटरनेट जाँचें और फिर कोशिश करें।',
    retry: 'फिर कोशिश करें',
    notFound: 'यह पन्ना नहीं मिला।',
    language: 'भाषा',
    textSize: 'अक्षर का आकार',
    smaller: 'छोटा',
    bigger: 'बड़ा',
    sizePreview: 'णमो अरिहंताणं',
    maxSize: 'यह सबसे बड़ा आकार है',
    minSize: 'यह सबसे छोटा आकार है',
    colours: 'रंग',
    day: 'दिन',
    night: 'रात',
    speed: 'सुनाने की गति',
    slow: 'धीमी',
    normal: 'सामान्य',
    fast: 'तेज़',
    roman: 'रोमन लिपि भी दिखाएँ',
    romanDesc: 'श्लोक के नीचे अंग्रेज़ी अक्षरों में भी दिखेगा',
    yes: 'हाँ',
    no: 'नहीं',
    install: 'फ़ोन में ऐप जोड़ें',
    installDesc: 'मुख्य स्क्रीन पर जिनवाणी का निशान आ जाएगा, और ऐप बिना इंटरनेट के भी चलेगा।',
    installIos: 'iPhone पर: नीचे "Share" बटन दबाएँ, फिर "Add to Home Screen" चुनें।',
    installed: 'ऐप फ़ोन में जुड़ा हुआ है',
    lock: 'सेटिंग लॉक',
    lockDesc: 'चालू करने पर भाषा, अक्षर का आकार और बाकी सेटिंग गलती से नहीं बदलेंगी।',
    lockOn: 'लॉक करें',
    lockedMsg: 'सेटिंग बंद हैं। खोलने के लिए नीचे का बटन 3 सेकंड दबाकर रखें।',
    holdToUnlock: 'दबाकर रखें',
    unlocked: 'सेटिंग खुल गईं',
    credits: 'आभार',
    creditsIntro: 'इस ऐप के पाठ और साधन इनसे लिए गए हैं। सबका हृदय से आभार।',
    textsHeading: 'पाठ',
    toolsHeading: 'अक्षर और चिह्न',
    fontCredit: 'नोटो सेरिफ़ देवनागरी अक्षर (Noto Serif Devanagari) — SIL Open Font License',
    iconCredit: 'चिह्न: Tabler Icons — MIT License',
    proofNote: 'हर पाठ सावधानी से जाँचा गया है। फिर भी कोई गलती दिखे तो पढ़ते समय "पाठ में गलती? बताएँ" दबाएँ।',
    licenseNote: 'पाठ CC BY-SA 4.0 के अंतर्गत, और ऐप का कोड MIT License के अंतर्गत है।',
    offlineReady: 'ऐप अब बिना इंटरनेट के भी चलेगा',
    count: '{n} {unit}',
    chapterShort: '{sec} {n}',
    position: '{unit} {n}',
    positionSec: '{sec} {s} · {unit} {n}',
    mistakeTitle: 'पाठ सुधार: {book}, {pos}',
    mistakeBody: 'अभी का पाठ:\n{text}\n\nसही पाठ / सुझाव:\n'
  },
  en: {
    appName: 'Jinvani',
    greeting: 'Jai Jinendra',
    chooseLang: 'Choose language',
    changeLater: 'You can change this later in Settings',
    continueReading: 'Continue reading',
    startReading: 'Start here',
    books: 'Books',
    search: 'Search',
    saved: 'Saved',
    settings: 'Settings',
    home: 'Home',
    back: 'Back',
    contents: 'Contents',
    prev: 'Previous',
    next: 'Next',
    finish: 'Finish',
    listen: 'Listen',
    stop: 'Stop',
    save: 'Save',
    savedDone: 'Saved',
    removed: 'Removed',
    remove: 'Remove',
    todaysSutra: "Today's sutra",
    readFromStart: 'Read from the start',
    resumeAt: 'Where you left off',
    goToNumber: 'Go to number',
    go: 'Go',
    numberHint: '1 to {n}',
    badNumber: 'Enter a number from 1 to {n}',
    meaning: 'Meaning',
    firstVerseNote: 'This is the first one',
    bookDone: 'Book completed',
    reportMistake: 'Mistake in the text? Report it',
    searchPlaceholder: 'e.g. Bhaktamar, samyagdarshan',
    speak: 'Search by voice',
    listening: 'Listening… speak now',
    noResults: 'Nothing found. Try another word.',
    resultsBooks: 'Books',
    resultsText: 'In the text',
    typeToSearch: 'Type a book name or any word, or tap the microphone and speak.',
    noBookmarks: 'Nothing saved yet. Tap "Save" while reading.',
    noVoice: 'No Hindi voice found on this phone. Add Hindi under "Text-to-speech" in the phone settings.',
    noSpeech: "This browser can't read aloud.",
    noMic: "Voice search isn't available in this browser. Type to search instead.",
    micDenied: 'Microphone permission was not given.',
    loading: 'Opening…',
    loadError: "Couldn't open. Check the internet and try again.",
    retry: 'Try again',
    notFound: "This page wasn't found.",
    language: 'Language',
    textSize: 'Text size',
    smaller: 'Smaller',
    bigger: 'Bigger',
    sizePreview: 'णमो अरिहंताणं',
    maxSize: 'This is the biggest size',
    minSize: 'This is the smallest size',
    colours: 'Colours',
    day: 'Day',
    night: 'Night',
    speed: 'Listening speed',
    slow: 'Slow',
    normal: 'Normal',
    fast: 'Fast',
    roman: 'Also show Roman script',
    romanDesc: 'Each verse is also shown in English letters',
    yes: 'Yes',
    no: 'No',
    install: 'Add app to phone',
    installDesc: 'Puts a Jinvani icon on the home screen, and the app works without internet.',
    installIos: 'On iPhone: tap the "Share" button at the bottom, then choose "Add to Home Screen".',
    installed: 'The app is on this phone',
    lock: 'Settings lock',
    lockDesc: "When on, language, text size and other settings can't be changed by mistake.",
    lockOn: 'Lock',
    lockedMsg: 'Settings are locked. Press and hold the button below for 3 seconds to unlock.',
    holdToUnlock: 'Press and hold',
    unlocked: 'Settings unlocked',
    credits: 'Credits',
    creditsIntro: 'The texts and tools in this app come from these sources, with gratitude.',
    textsHeading: 'Texts',
    toolsHeading: 'Fonts and icons',
    fontCredit: 'Noto Serif Devanagari font — SIL Open Font License',
    iconCredit: 'Icons: Tabler Icons — MIT License',
    proofNote: 'Every text has been checked carefully. If you still see a mistake, tap "Mistake in the text? Report it" while reading.',
    licenseNote: 'Texts are under CC BY-SA 4.0, and the app code is under the MIT License.',
    offlineReady: 'The app now works without internet',
    count: '{n} {unit}s',
    chapterShort: '{sec} {n}',
    position: '{unit} {n}',
    positionSec: '{sec} {s} · {unit} {n}',
    mistakeTitle: 'Text correction: {book}, {pos}',
    mistakeBody: 'Current text:\n{text}\n\nCorrect text / suggestion:\n'
  }
};
