/*
 * All words shown in the app, in each language.
 * To add a language, copy the "en" block, give it a new code (for example "gu"),
 * translate the right-hand side, and add the code to LANGS below.
 */
const LANGS = [
  { code: 'hi', name: 'हिंदी' },
  { code: 'en', name: 'English' }
];

const STRINGS = {
  hi: {
    appName: 'स्वाध्याय',
    greeting: 'जय जिनेन्द्र',
    chooseLang: 'भाषा चुनें',
    changeLater: 'बाद में सेटिंग में बदल सकते हैं',
    continueReading: 'पढ़ना जारी रखें',
    startReading: 'यहाँ से शुरू करें',
    books: 'ग्रंथ',
    search: 'खोजें',
    saved: 'सहेजे गए',
    settings: 'सेटिंग',
    home: 'मुख्य',
    back: 'वापस',
    contents: 'सूची',
    prev: 'पीछे',
    next: 'आगे',
    finish: 'समाप्त',
    listen: 'सुनें',
    stop: 'रोकें',
    save: 'सहेजें',
    savedDone: 'सहेजा गया',
    removed: 'हटा दिया',
    remove: 'हटाएँ',
    todaysSutra: 'आज का सूत्र',
    todaysStory: 'आज की कथा',
    moral: 'कथा की सीख',
    readFromStart: 'शुरू से पढ़ें',
    resumeAt: 'जहाँ छोड़ा था',
    goToNumber: 'नंबर पर जाएँ',
    go: 'जाएँ',
    numberHint: '1 से {n} तक',
    badNumber: '1 से {n} के बीच नंबर लिखें',
    meaning: 'अर्थ',
    firstVerseNote: 'यह पहला है',
    bookDone: 'ग्रंथ पूर्ण हुआ',
    reportMistake: 'पाठ में गलती? बताएँ',
    searchPlaceholder: 'जैसे: भक्तामर, सम्यग्दर्शन',
    speak: 'बोलकर खोजें',
    listening: 'सुन रहे हैं… बोलिए',
    noResults: 'कुछ नहीं मिला। दूसरा शब्द लिखकर देखें।',
    resultsBooks: 'ग्रंथ',
    resultsText: 'पाठ में',
    typeToSearch: 'ग्रंथ का नाम या कोई शब्द लिखें, या माइक दबाकर बोलें।',
    noBookmarks: 'अभी कुछ सहेजा नहीं गया। पढ़ते समय "सहेजें" दबाएँ।',
    noVoice: 'इस फ़ोन में हिंदी आवाज़ नहीं मिली। फ़ोन की सेटिंग में "Text-to-speech" में हिंदी जोड़ें।',
    noSpeech: 'इस ब्राउज़र में सुनने की सुविधा नहीं है।',
    noMic: 'इस ब्राउज़र में बोलकर खोजना उपलब्ध नहीं है। लिखकर खोजें।',
    micDenied: 'माइक की अनुमति नहीं मिली।',
    loading: 'खुल रहा है…',
    loadError: 'खुल नहीं पाया। इंटरनेट जाँचें और फिर कोशिश करें।',
    retry: 'फिर कोशिश करें',
    notFound: 'यह पन्ना नहीं मिला।',
    language: 'भाषा',
    textSize: 'अक्षर का आकार',
    smaller: 'छोटा',
    bigger: 'बड़ा',
    sizePreview: 'णमो अरिहंताणं',
    maxSize: 'यह सबसे बड़ा आकार है',
    minSize: 'यह सबसे छोटा आकार है',
    colours: 'रंग',
    day: 'दिन',
    night: 'रात',
    speed: 'सुनाने की गति',
    slow: 'धीमी',
    normal: 'सामान्य',
    fast: 'तेज़',
    roman: 'रोमन लिपि भी दिखाएँ',
    romanDesc: 'श्लोक के नीचे अंग्रेज़ी अक्षरों में भी दिखेगा',
    yes: 'हाँ',
    no: 'नहीं',
    install: 'फ़ोन में ऐप जोड़ें',
    installDesc: 'मुख्य स्क्रीन पर स्वाध्याय का निशान आ जाएगा, और ऐप बिना इंटरनेट के भी चलेगा।',
    installIos: 'iPhone पर: नीचे "Share" बटन दबाएँ, फिर "Add to Home Screen" चुनें।',
    installed: 'ऐप फ़ोन में जुड़ा हुआ है',
    lock: 'सेटिंग लॉक',
    lockDesc: 'चालू करने पर भाषा, अक्षर का आकार और बाकी सेटिंग गलती से नहीं बदलेंगी।',
    lockOn: 'लॉक करें',
    lockedMsg: 'सेटिंग बंद हैं। खोलने के लिए नीचे का बटन 3 सेकंड दबाकर रखें।',
    holdToUnlock: 'दबाकर रखें',
    unlocked: 'सेटिंग खुल गईं',
    credits: 'आभार',
    ask: 'प्रश्न पूछें',
    askIntro: 'जैन धर्म के बारे में कुछ भी पूछें। उत्तर इसी ऐप के ग्रंथों से दिए जाते हैं, और साथ में बताया जाता है कि कहाँ पढ़ें।',
    askLabel: 'आपका प्रश्न',
    askPlaceholder: 'जैसे: रत्नत्रय क्या है?',
    askButton: 'पूछें',
    askThinking: 'ग्रंथों में उत्तर खोजा जा रहा है',
    askFromFaq: 'सामान्य प्रश्न',
    askFromTexts: 'ग्रंथों के आधार पर उत्तर',
    askSources: 'कहाँ पढ़ें',
    askOpen: 'उसी स्थान पर खोलें',
    askCheck: 'यह उत्तर ऐप के ग्रंथों से कंप्यूटर (AI) ने तैयार किया है। संदेह हो तो ग्रंथ से मिला लें या किसी विद्वान से पूछें।',
    askAiInstead: 'यह नहीं पूछा था? ग्रंथों से उत्तर लें',
    askOff: 'अभी केवल सामान्य प्रश्नों के उत्तर मिलते हैं। नीचे दिए प्रश्न देखें, या दूसरे शब्दों में पूछें।',
    askOffline: 'इंटरनेट नहीं है। सामान्य प्रश्नों के उत्तर बिना इंटरनेट भी मिलते हैं; नीचे देखें।',
    askBusy: 'अभी बहुत प्रश्न आ रहे हैं। थोड़ी देर बाद फिर पूछें।',
    askFailed: 'उत्तर नहीं मिल सका। थोड़ी देर बाद फिर कोशिश करें।',
    askShort: 'प्रश्न थोड़ा और लिखें।',
    askPrivacy: 'नए प्रश्न उत्तर के लिए हमारे सर्वर और NVIDIA को भेजे जाते हैं। उनमें अपना नाम या निजी बात न लिखें।',
    askRelated: 'मिलते-जुलते प्रश्न',
    askCommon: 'अक्सर पूछे जाने वाले प्रश्न',
    askHistory: 'आपके पिछले प्रश्न',
    askFromSearch: 'कोई प्रश्न है? पूछें',
    pathAsk: 'प्रश्न पूछें',
    pathAskSub: 'जैन धर्म के बारे में, ग्रंथों से उत्तर',
    madeBy: 'श्रद्धा सहित निर्मित',
    makerName: 'आर्जव टोंग्या',
    makerPlace: 'इंदौर',
    makerAbout: 'जय जिनेन्द्र! मैं इंदौर से हूँ। मैंने स्वाध्याय ऐप इसलिए बनाया कि जैन धर्म को जानने और जीने के लिए जो कुछ चाहिए, चाहे नित्य पाठ हो, पूजा, ग्रंथ, कथाएँ, मंदिर की विधि या तिथि, वह सब एक ही जगह मिल जाए, और घर हो या मंदिर, स्वाध्याय कभी न छूटे।',
    makerWrite: 'कोई भूल दिखे या सुझाव हो तो लिखें',
    creditsIntro: 'इस ऐप के पाठ और साधन इनसे लिए गए हैं। सबका हृदय से आभार।',
    textsHeading: 'पाठ',
    toolsHeading: 'अक्षर और चिह्न',
    fontCredit: 'अक्षर: वेस्पर लिब्रे (Vesper Libre), हिन्द (Hind) और नोटो सेरिफ़ देवनागरी (Noto Serif Devanagari) — SIL Open Font License',
    iconCredit: 'चिह्न: स्वाध्याय के अपने चिह्न, और Tabler Icons — MIT License',
    proofNote: 'हर पाठ सावधानी से जाँचा गया है। फिर भी कहीं संदेह हो तो अपने मंदिर की पुस्तक या पंडित जी से मिला लें।',
    licenseNote: 'पाठ CC BY-SA 4.0 के अंतर्गत, और ऐप का कोड MIT License के अंतर्गत है।',
    offlineReady: 'ऐप अब बिना इंटरनेट के भी चलेगा',
    count: '{n} {unit}',
    chapterShort: '{sec} {n}',
    position: '{unit} {n}',
    positionSec: '{sec} {s} · {unit} {n}',
    mistakeTitle: 'पाठ सुधार: {book}, {pos}',
    mistakeBody: 'अभी का पाठ:\n{text}\n\nसही पाठ / सुझाव:\n',
    invocation: 'मंगलाचरण',
    padya: 'पद्यानुवाद',
    chitraLabel: 'चित्र से समझें',
    gist: 'सार',
    poojaGuide: 'पूजा विधि',
    mandirGuide: 'मंदिर दर्शन',
    today: 'आज',
    tomorrow: 'कल',
    weekOpen: 'अगले 7 दिन देखें',
    weekClose: 'बंद करें',
    scrollMore: 'नीचे और है',
    tithiNote: 'तिथि दिल्ली के सूर्योदय के अनुसार (पूर्णिमान्त मास)। व्रत-पर्व के लिए अपने मंदिर का पंचांग भी देख लें।',
    parva: 'पर्व',
    adhik: 'अधिक',
    tithis: ['प्रतिपदा', 'द्वितीया', 'तृतीया', 'चतुर्थी', 'पंचमी', 'षष्ठी', 'सप्तमी', 'अष्टमी', 'नवमी', 'दशमी', 'एकादशी', 'द्वादशी', 'त्रयोदशी', 'चतुर्दशी', 'पूर्णिमा', 'अमावस्या'],
    paksha: { shukla: 'शुक्ल', krishna: 'कृष्ण' },
    months: ['चैत्र', 'वैशाख', 'ज्येष्ठ', 'आषाढ़', 'श्रावण', 'भाद्रपद', 'आश्विन', 'कार्तिक', 'मार्गशीर्ष', 'पौष', 'माघ', 'फाल्गुन'],
    festivals: {
      mahavirJayanti: 'महावीर जयंती',
      akshayaTritiya: 'अक्षय तृतीया',
      shrutPanchami: 'श्रुत पंचमी',
      ashtahnika: 'अष्टाह्निका पर्व',
      veerShasan: 'वीर शासन जयंती',
      mokshSaptami: 'मोक्ष सप्तमी',
      rakshaBandhan: 'रक्षाबंधन',
      dasLakshan: 'दशलक्षण पर्व',
      anantChaturdashi: 'अनन्त चतुर्दशी',
      kshamavani: 'क्षमावाणी',
      diwali: 'दीपावली · वीर निर्वाण'
    },
    booksCount: '{n} ग्रंथ',
    readSectionFromStart: 'यह {sec} शुरू से पढ़ें',
    searchScope: 'पाठ में खोज केवल उन ग्रंथों में होती है जो इस फ़ोन पर एक बार खुल चुके हैं। बाकी ग्रंथ नाम से खोजे जा सकते हैं।',
    autoTheme: 'फ़ोन के अनुसार',
    share: 'साझा करें',
    copied: 'पाठ कॉपी हो गया। अब WhatsApp या संदेश में चिपकाएँ।',
    copyFailed: 'कॉपी नहीं हो पाया। पाठ को दबाकर रखें और "Copy" चुनें।',
    shareFrom: 'स्वाध्याय ऐप से',
    orPick: 'या कोई ग्रंथ चुनें',
    seeBooks: 'ग्रंथ देखें',
    swipeHint: 'पन्ना बदलने के लिए स्क्रीन पर उँगली बाएँ भी सरका सकते हैं',
    sizeLevel: 'आकार {n} / {max}',
    savedCount: '{n} सहेजे गए',
    ofTotal: '{n} में से',
    pakshaWord: 'पक्ष',
    weekLabel: 'अगले 7 दिन',
    noParva: 'अगले 7 दिन में अष्टमी या चतुर्दशी नहीं है',
    pathNitya: 'नित्य पाठ',
    pathNityaSub: 'णमोकार, भक्तामर, दर्शन पाठ और तत्त्वार्थसूत्र',
    pathPooja: 'पूजा और आरती',
    pathPoojaSub: '{n} पूजाएँ, अर्घ्य, विसर्जन और आरती',
    pathPath: 'पाठ और स्तोत्र',
    pathPathSub: '{n} पाठ, भावना और स्तोत्र',
    pathGranth: 'ग्रंथ',
    pathGranthSub: 'चारों अनुयोगों के {n} शास्त्र',
    pathKatha: 'जैन कथाएँ',
    pathKathaSub: '{n} कथाएँ, चित्रों के साथ',
    pathVidhi: 'मंदिर दर्शन और पूजा विधि',
    pathVidhiSub: 'हर चरण चित्र के साथ',
    pathSavedNone: 'पढ़ते समय "सहेजें" दबाएँ',
    shelfNitya: 'नित्य पाठ और विधि',
    shelfPooja: 'पूजा',
    shelfPath: 'पाठ और स्तोत्र',
    shelfGranth: 'ग्रंथ — चार अनुयोग',
    shelfKatha: 'कथाएँ',
    shelfOther: 'अन्य',
    help: 'कैसे चलाएँ',
    helpTips: [
      '"आगे" और "पीछे" बटन से पन्ना बदलें, या स्क्रीन पर उँगली बाएँ-दाएँ सरकाएँ।',
      '"सुनें" दबाने पर पाठ आवाज़ में सुनाई देगा और अगला पन्ना अपने आप खुलेगा।',
      'पढ़ते समय "सहेजें" दबाएँ, वह पाठ "सहेजे गए" में मिलेगा।',
      'ऐप याद रखता है कि आपने कहाँ छोड़ा था। मुख्य स्क्रीन पर "पढ़ना जारी रखें" दबाएँ।',
      'नीचे की पट्टी से किसी भी समय मुख्य, ग्रंथ, खोज या सेटिंग पर जाएँ।'
    ],
    partNames: {}
  },
  en: {
    appName: 'Swadhyay',
    greeting: 'Jai Jinendra',
    chooseLang: 'Choose language',
    changeLater: 'You can change this later in Settings',
    continueReading: 'Continue reading',
    startReading: 'Start here',
    books: 'Books',
    search: 'Search',
    saved: 'Saved',
    settings: 'Settings',
    home: 'Home',
    back: 'Back',
    contents: 'Contents',
    prev: 'Previous',
    next: 'Next',
    finish: 'Finish',
    listen: 'Listen',
    stop: 'Stop',
    save: 'Save',
    savedDone: 'Saved',
    removed: 'Removed',
    remove: 'Remove',
    todaysSutra: "Today's sutra",
    todaysStory: "Today's story",
    moral: 'The lesson',
    readFromStart: 'Read from the start',
    resumeAt: 'Where you left off',
    goToNumber: 'Go to number',
    go: 'Go',
    numberHint: '1 to {n}',
    badNumber: 'Enter a number from 1 to {n}',
    meaning: 'Meaning',
    firstVerseNote: 'This is the first one',
    bookDone: 'Book completed',
    reportMistake: 'Mistake in the text? Report it',
    searchPlaceholder: 'e.g. Bhaktamar, samyagdarshan',
    speak: 'Search by voice',
    listening: 'Listening… speak now',
    noResults: 'Nothing found. Try another word.',
    resultsBooks: 'Books',
    resultsText: 'In the text',
    typeToSearch: 'Type a book name or any word, or tap the microphone and speak.',
    noBookmarks: 'Nothing saved yet. Tap "Save" while reading.',
    noVoice: 'No Hindi voice found on this phone. Add Hindi under "Text-to-speech" in the phone settings.',
    noSpeech: "This browser can't read aloud.",
    noMic: "Voice search isn't available in this browser. Type to search instead.",
    micDenied: 'Microphone permission was not given.',
    loading: 'Opening…',
    loadError: "Couldn't open. Check the internet and try again.",
    retry: 'Try again',
    notFound: "This page wasn't found.",
    language: 'Language',
    textSize: 'Text size',
    smaller: 'Smaller',
    bigger: 'Bigger',
    sizePreview: 'णमो अरिहंताणं',
    maxSize: 'This is the biggest size',
    minSize: 'This is the smallest size',
    colours: 'Colours',
    day: 'Day',
    night: 'Night',
    speed: 'Listening speed',
    slow: 'Slow',
    normal: 'Normal',
    fast: 'Fast',
    roman: 'Also show Roman script',
    romanDesc: 'Each verse is also shown in English letters',
    yes: 'Yes',
    no: 'No',
    install: 'Add app to phone',
    installDesc: 'Puts a Swadhyay icon on the home screen, and the app works without internet.',
    installIos: 'On iPhone: tap the "Share" button at the bottom, then choose "Add to Home Screen".',
    installed: 'The app is on this phone',
    lock: 'Settings lock',
    lockDesc: "When on, language, text size and other settings can't be changed by mistake.",
    lockOn: 'Lock',
    lockedMsg: 'Settings are locked. Press and hold the button below for 3 seconds to unlock.',
    holdToUnlock: 'Press and hold',
    unlocked: 'Settings unlocked',
    credits: 'Credits',
    ask: 'Ask a question',
    askIntro: 'Ask anything about Jain dharma. Answers come from the texts in this app, with where to read more.',
    askLabel: 'Your question',
    askPlaceholder: 'For example: What is ratnatraya?',
    askButton: 'Ask',
    askThinking: 'Looking for the answer in the texts',
    askFromFaq: 'Common question',
    askFromTexts: 'Answered from the texts',
    askSources: 'Read more',
    askOpen: 'Open at this place',
    askCheck: 'This answer was put together by AI from the app\'s texts. If anything seems doubtful, check the text or ask a learned person.',
    askAiInstead: 'Not what you asked? Get an answer from the texts',
    askOff: 'For now, only the common questions are answered. See the questions below, or try other words.',
    askOffline: 'No internet. The common questions below are answered even offline.',
    askBusy: 'Many questions are coming in right now. Please ask again in a little while.',
    askFailed: 'Could not get an answer. Please try again in a little while.',
    askShort: 'Please write a little more.',
    askPrivacy: 'New questions are sent to our server and to NVIDIA to be answered. Please leave out names and personal details.',
    askRelated: 'Related questions',
    askCommon: 'Common questions',
    askHistory: 'Your earlier questions',
    askFromSearch: 'Have a question? Ask',
    pathAsk: 'Ask a question',
    pathAskSub: 'About Jain dharma, answered from the texts',
    madeBy: 'Made with devotion by',
    makerName: 'Arjav Tongia',
    makerPlace: 'Indore',
    makerAbout: 'Jai Jinendra! I am from Indore. I made the Swadhyay app so that everything one needs to learn and live Jain dharma, be it the daily prayers, poojas, granths, stories, temple guides or the tithi, is in one place, and swadhyay is never missed, whether at home or in the temple.',
    makerWrite: 'Found a mistake or have a suggestion? Write to me',
    creditsIntro: 'The texts and tools in this app come from these sources, with gratitude.',
    textsHeading: 'Texts',
    toolsHeading: 'Fonts and icons',
    fontCredit: 'Fonts: Vesper Libre, Hind and Noto Serif Devanagari — SIL Open Font License',
    iconCredit: 'Icons: the Swadhyay icon pack, and Tabler Icons — MIT License',
    proofNote: 'Every text has been checked carefully. If anything seems doubtful, compare it with the book at your temple or ask the pandit ji.',
    licenseNote: 'Texts are under CC BY-SA 4.0, and the app code is under the MIT License.',
    offlineReady: 'The app now works without internet',
    count: '{n} {unit}s',
    chapterShort: '{sec} {n}',
    position: '{unit} {n}',
    positionSec: '{sec} {s} · {unit} {n}',
    mistakeTitle: 'Text correction: {book}, {pos}',
    mistakeBody: 'Current text:\n{text}\n\nCorrect text / suggestion:\n',
    invocation: 'Invocation',
    padya: 'Hindi verse translation',
    chitraLabel: 'Understand with a picture',
    gist: 'In short',
    poojaGuide: 'Pooja guide',
    mandirGuide: 'Temple visit',
    today: 'Today',
    tomorrow: 'Tomorrow',
    weekOpen: 'See the next 7 days',
    weekClose: 'Close',
    scrollMore: 'More below',
    tithiNote: 'Tithi at sunrise in Delhi (purnimanta months). For fasts and festivals, also check your temple calendar.',
    parva: 'Parva',
    adhik: 'Adhik',
    tithis: ['Pratipada', 'Dwitiya', 'Tritiya', 'Chaturthi', 'Panchami', 'Shashthi', 'Saptami', 'Ashtami', 'Navami', 'Dashami', 'Ekadashi', 'Dwadashi', 'Trayodashi', 'Chaturdashi', 'Purnima', 'Amavasya'],
    paksha: { shukla: 'Shukla', krishna: 'Krishna' },
    months: ['Chaitra', 'Vaishakh', 'Jyeshtha', 'Ashadh', 'Shravan', 'Bhadrapad', 'Ashwin', 'Kartik', 'Margashirsha', 'Paush', 'Magh', 'Phalgun'],
    festivals: {
      mahavirJayanti: 'Mahavir Jayanti',
      akshayaTritiya: 'Akshaya Tritiya',
      shrutPanchami: 'Shrut Panchami',
      ashtahnika: 'Ashtahnika Parva',
      veerShasan: 'Veer Shasan Jayanti',
      mokshSaptami: 'Moksh Saptami',
      rakshaBandhan: 'Raksha Bandhan',
      dasLakshan: 'Dashlakshan Parva',
      anantChaturdashi: 'Anant Chaturdashi',
      kshamavani: 'Kshamavani',
      diwali: 'Diwali · Veer Nirvan'
    },
    booksCount: '{n} books',
    readSectionFromStart: 'Read this {sec} from the start',
    searchScope: 'Text search covers only the books already opened once on this phone. Other books can be found by name.',
    autoTheme: 'Same as phone',
    share: 'Share',
    copied: 'Text copied. Paste it in WhatsApp or a message.',
    copyFailed: 'Could not copy. Press and hold the text and choose "Copy".',
    shareFrom: 'From the Swadhyay app',
    orPick: 'Or pick a book',
    seeBooks: 'See the books',
    swipeHint: 'You can also swipe left on the screen to turn the page',
    sizeLevel: 'Size {n} of {max}',
    savedCount: '{n} saved',
    ofTotal: 'of {n}',
    pakshaWord: 'paksha',
    weekLabel: 'The next 7 days',
    noParva: 'No ashtami or chaturdashi in the next 7 days',
    pathNitya: 'Daily prayers',
    pathNityaSub: 'Namokar, Bhaktamar, Darshan Path and Tattvarth Sutra',
    pathPooja: 'Poojas and aarti',
    pathPoojaSub: '{n} poojas, arghya, visarjan and aarti',
    pathPath: 'Paath and stotras',
    pathPathSub: '{n} paath, bhavanas and stotras',
    pathGranth: 'Scriptures',
    pathGranthSub: '{n} scriptures from the four anuyogs',
    pathKatha: 'Jain stories',
    pathKathaSub: '{n} stories with pictures',
    pathVidhi: 'Temple visit and pooja guides',
    pathVidhiSub: 'Every step with a picture',
    pathSavedNone: 'Tap "Save" while reading',
    shelfNitya: 'Daily prayers and guides',
    shelfPooja: 'Poojas',
    shelfPath: 'Paath and stotras',
    shelfGranth: 'Scriptures — the four anuyogs',
    shelfKatha: 'Stories',
    shelfOther: 'Other',
    help: 'How to use',
    helpTips: [
      'Use the "Next" and "Previous" buttons to turn pages, or swipe left and right on the screen.',
      'Tap "Listen" to hear the text read aloud; the next page opens by itself.',
      'Tap "Save" while reading to find that text later under "Saved".',
      'The app remembers where you stopped. Tap "Continue reading" on the home screen.',
      'The bar at the bottom takes you to Home, Books, Search or Settings at any time.'
    ],
    partNames: {
      'अन्वयार्थ': 'Word-by-word meaning',
      'अर्थ': 'Meaning',
      'भावार्थ': 'Essence',
      'विशेषार्थ': 'Explanation',
      'विशेष': 'Note'
    }
  }
};
